### ISSUE TITLE
bug in blogspot

### ISSUE THREAD

**Issue by sajad22** [hamano/regdom4j#1]
why when we send blogspot.com you return null?

tnx

**Comment by hamano** [comment]
Hi,
regdom4j is based on "Effective TLD" that maintain Mozilla.
see: http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1

I don't know background that including blogspot.com, But
Probably anyone can register *.blogspot.com subdomain.
Therefore, You must not set domain cookie for blogspot.com.
It called an Effective TLD.
